[package]
name = "rbuwu"
version = "0.0.6-ALPHA"
edition = "2021"
description = "rust macros but in uwu"
license = "GPL-3.0"
repository = "https://github.com/mrtuxa/rbuwu"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
