name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  example:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cd example && cargo build --verbose
      - name: Run tests
        run: cd example && cargo test --verbose
      - name: Run binary
        run: cd example && cargo run --verbose
